Added PQC algorithms

diff --git a/easyrsa3/easyrsa b/easyrsa3/easyrsa
--- a/easyrsa3/easyrsa
+++ b/easyrsa3/easyrsa
@@ -1479,6 +1479,14 @@ Please update openssl-easyrsa.cnf to the latest official release."
 				${out_key_pass_tmp:+ -pass file:"$out_key_pass_tmp"} \
 					|| die "Failed create CA private key"
 		;;
+        pqc)
+            easyrsa_openssl genpkey -algorithm "$EASYRSA_PQC_ALGO" \
+                -out "$out_key_tmp" \
+				${cipher+ "$cipher"} \
+				${EASYRSA_PASSOUT:+ -pass "$EASYRSA_PASSOUT"} \
+				${out_key_pass_tmp:+ -pass file:"$out_key_pass_tmp"} \
+					|| die "Failed create CA private key"
+        ;; 
 		*)	die "Unknown algorithm: $EASYRSA_ALGO"
 		esac
 
@@ -4300,6 +4308,8 @@ Failed to generate ecparam file (permissions?) at:
 			> /dev/null || die "\
 Edwards Curve $EASYRSA_CURVE not found."
 	;;
+    pqc)
+    ;;
 	*) die "\
 Alg '$EASYRSA_ALGO' is invalid: Must be 'rsa', 'ec' or 'ed'"
 	esac
@@ -4492,7 +4502,9 @@ Sourcing the vars file and building certificates will probably fail ..'
 	ed)
 		set_var EASYRSA_CURVE		ed25519
 	;;
-	*) die "Unknown algorithm '$EASYRSA_ALGO'"
+    pqc)
+    ;;
+    *) die "Unknown algorithm '$EASYRSA_ALGO'"
 	esac
 
 	set_var EASYRSA_CA_EXPIRE		3650
